/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SvgsRouteImport } from './routes/svgs'
import { Route as MigrationsRouteImport } from './routes/migrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as DatabasesRouteImport } from './routes/databases'
import { Route as ProjectSlugRouteImport } from './routes/$projectSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as ProjectSlugIndexRouteImport } from './routes/$projectSlug/index'
import { Route as SettingsSettingsPageRouteImport } from './routes/settings/$settingsPage'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding/success'
import { Route as ProjectSlugServiceSlugRouteImport } from './routes/$projectSlug/$serviceSlug'
import { Route as ProjectSlugServiceSlugIndexRouteImport } from './routes/$projectSlug/$serviceSlug/index'
import { Route as ProjectSlugServiceSlugServiceTabRouteImport } from './routes/$projectSlug/$serviceSlug/$serviceTab'

const SvgsRoute = SvgsRouteImport.update({
  id: '/svgs',
  path: '/svgs',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationsRoute = MigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesRoute = DatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugIndexRoute = ProjectSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const SettingsSettingsPageRoute = SettingsSettingsPageRouteImport.update({
  id: '/settings/$settingsPage',
  path: '/settings/$settingsPage',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/onboarding/success',
  path: '/onboarding/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugServiceSlugRoute = ProjectSlugServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugServiceSlugIndexRoute =
  ProjectSlugServiceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectSlugServiceSlugRoute,
  } as any)
const ProjectSlugServiceSlugServiceTabRoute =
  ProjectSlugServiceSlugServiceTabRouteImport.update({
    id: '/$serviceTab',
    path: '/$serviceTab',
    getParentRoute: () => ProjectSlugServiceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectSlug': typeof ProjectSlugRouteWithChildren
  '/databases': typeof DatabasesRoute
  '/deployments': typeof DeploymentsRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/migrations': typeof MigrationsRoute
  '/svgs': typeof SvgsRoute
  '/$projectSlug/$serviceSlug': typeof ProjectSlugServiceSlugRouteWithChildren
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/settings/$settingsPage': typeof SettingsSettingsPageRoute
  '/$projectSlug/': typeof ProjectSlugIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/$projectSlug/$serviceSlug/$serviceTab': typeof ProjectSlugServiceSlugServiceTabRoute
  '/$projectSlug/$serviceSlug/': typeof ProjectSlugServiceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/databases': typeof DatabasesRoute
  '/deployments': typeof DeploymentsRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/migrations': typeof MigrationsRoute
  '/svgs': typeof SvgsRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/settings/$settingsPage': typeof SettingsSettingsPageRoute
  '/$projectSlug': typeof ProjectSlugIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/$projectSlug/$serviceSlug/$serviceTab': typeof ProjectSlugServiceSlugServiceTabRoute
  '/$projectSlug/$serviceSlug': typeof ProjectSlugServiceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectSlug': typeof ProjectSlugRouteWithChildren
  '/databases': typeof DatabasesRoute
  '/deployments': typeof DeploymentsRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/migrations': typeof MigrationsRoute
  '/svgs': typeof SvgsRoute
  '/$projectSlug/$serviceSlug': typeof ProjectSlugServiceSlugRouteWithChildren
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/settings/$settingsPage': typeof SettingsSettingsPageRoute
  '/$projectSlug/': typeof ProjectSlugIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/$projectSlug/$serviceSlug/$serviceTab': typeof ProjectSlugServiceSlugServiceTabRoute
  '/$projectSlug/$serviceSlug/': typeof ProjectSlugServiceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectSlug'
    | '/databases'
    | '/deployments'
    | '/domains'
    | '/login'
    | '/migrations'
    | '/svgs'
    | '/$projectSlug/$serviceSlug'
    | '/onboarding/success'
    | '/settings/$settingsPage'
    | '/$projectSlug/'
    | '/onboarding/'
    | '/projects/'
    | '/settings/'
    | '/$projectSlug/$serviceSlug/$serviceTab'
    | '/$projectSlug/$serviceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/databases'
    | '/deployments'
    | '/domains'
    | '/login'
    | '/migrations'
    | '/svgs'
    | '/onboarding/success'
    | '/settings/$settingsPage'
    | '/$projectSlug'
    | '/onboarding'
    | '/projects'
    | '/settings'
    | '/$projectSlug/$serviceSlug/$serviceTab'
    | '/$projectSlug/$serviceSlug'
  id:
    | '__root__'
    | '/'
    | '/$projectSlug'
    | '/databases'
    | '/deployments'
    | '/domains'
    | '/login'
    | '/migrations'
    | '/svgs'
    | '/$projectSlug/$serviceSlug'
    | '/onboarding/success'
    | '/settings/$settingsPage'
    | '/$projectSlug/'
    | '/onboarding/'
    | '/projects/'
    | '/settings/'
    | '/$projectSlug/$serviceSlug/$serviceTab'
    | '/$projectSlug/$serviceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectSlugRoute: typeof ProjectSlugRouteWithChildren
  DatabasesRoute: typeof DatabasesRoute
  DeploymentsRoute: typeof DeploymentsRoute
  DomainsRoute: typeof DomainsRoute
  LoginRoute: typeof LoginRoute
  MigrationsRoute: typeof MigrationsRoute
  SvgsRoute: typeof SvgsRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
  SettingsSettingsPageRoute: typeof SettingsSettingsPageRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/svgs': {
      id: '/svgs'
      path: '/svgs'
      fullPath: '/svgs'
      preLoaderRoute: typeof SvgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrations': {
      id: '/migrations'
      path: '/migrations'
      fullPath: '/migrations'
      preLoaderRoute: typeof MigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases': {
      id: '/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug': {
      id: '/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/$projectSlug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/': {
      id: '/$projectSlug/'
      path: '/'
      fullPath: '/$projectSlug/'
      preLoaderRoute: typeof ProjectSlugIndexRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/settings/$settingsPage': {
      id: '/settings/$settingsPage'
      path: '/settings/$settingsPage'
      fullPath: '/settings/$settingsPage'
      preLoaderRoute: typeof SettingsSettingsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/onboarding/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectSlug/$serviceSlug': {
      id: '/$projectSlug/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/$projectSlug/$serviceSlug'
      preLoaderRoute: typeof ProjectSlugServiceSlugRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/$projectSlug/$serviceSlug/': {
      id: '/$projectSlug/$serviceSlug/'
      path: '/'
      fullPath: '/$projectSlug/$serviceSlug/'
      preLoaderRoute: typeof ProjectSlugServiceSlugIndexRouteImport
      parentRoute: typeof ProjectSlugServiceSlugRoute
    }
    '/$projectSlug/$serviceSlug/$serviceTab': {
      id: '/$projectSlug/$serviceSlug/$serviceTab'
      path: '/$serviceTab'
      fullPath: '/$projectSlug/$serviceSlug/$serviceTab'
      preLoaderRoute: typeof ProjectSlugServiceSlugServiceTabRouteImport
      parentRoute: typeof ProjectSlugServiceSlugRoute
    }
  }
}

interface ProjectSlugServiceSlugRouteChildren {
  ProjectSlugServiceSlugServiceTabRoute: typeof ProjectSlugServiceSlugServiceTabRoute
  ProjectSlugServiceSlugIndexRoute: typeof ProjectSlugServiceSlugIndexRoute
}

const ProjectSlugServiceSlugRouteChildren: ProjectSlugServiceSlugRouteChildren =
  {
    ProjectSlugServiceSlugServiceTabRoute:
      ProjectSlugServiceSlugServiceTabRoute,
    ProjectSlugServiceSlugIndexRoute: ProjectSlugServiceSlugIndexRoute,
  }

const ProjectSlugServiceSlugRouteWithChildren =
  ProjectSlugServiceSlugRoute._addFileChildren(
    ProjectSlugServiceSlugRouteChildren,
  )

interface ProjectSlugRouteChildren {
  ProjectSlugServiceSlugRoute: typeof ProjectSlugServiceSlugRouteWithChildren
  ProjectSlugIndexRoute: typeof ProjectSlugIndexRoute
}

const ProjectSlugRouteChildren: ProjectSlugRouteChildren = {
  ProjectSlugServiceSlugRoute: ProjectSlugServiceSlugRouteWithChildren,
  ProjectSlugIndexRoute: ProjectSlugIndexRoute,
}

const ProjectSlugRouteWithChildren = ProjectSlugRoute._addFileChildren(
  ProjectSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectSlugRoute: ProjectSlugRouteWithChildren,
  DatabasesRoute: DatabasesRoute,
  DeploymentsRoute: DeploymentsRoute,
  DomainsRoute: DomainsRoute,
  LoginRoute: LoginRoute,
  MigrationsRoute: MigrationsRoute,
  SvgsRoute: SvgsRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
  SettingsSettingsPageRoute: SettingsSettingsPageRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
